    export const allFundraisers = [
  {
    id: 1,
    title: "Pucci",
    breed: "Pomeranian",
    age: "Adult",
    description: "Pucci is a stylish and energetic companion who loves the spotlight.",
    goal: 1000,
    amount_raised: 0,
    image: "https://res.cloudinary.com/dqt5mriuz/image/upload/v1775552409/850_8109_m5kqx5.jpg",
    is_open: true,
    date_created: "2026-04-07T14:22:23Z",
    owner: 1,
    pledges: [],
  },
  {
    id: 2,
    title: "Mojo",
    breed: "Pomeranian",
    age: "11 years old",
    description: "Mojo is a funny fellow who loves snuggles and belly rubs.",
    goal: 1000,
    amount_raised: 0,
    image: "https://res.cloudinary.com/dqt5mriuz/image/upload/v1775553415/Mojo_ebwov9.jpg",
    is_open: true,
    date_created: "2026-04-07T14:22:23Z",
    owner: 1,
    pledges: [],
  },
  {
    id: 3,
    title: "ZaZa",
    breed: "Mixed",
    age: "Young",
    description: "ZaZa is full of life and looking for an active family to join.",
    goal: 1500,
    amount_raised: 0,
    image: "https://res.cloudinary.com/dqt5mriuz/image/upload/v1775553440/ZaZa_ree5hg.jpg",
    is_open: true,
    date_created: "2026-04-07T14:22:23Z",
    owner: 1,
    pledges: [],
  },
  {
    id: 4,
    title: "Rocky",
    breed: "Bulldog",
    age: "Senior",
    description: "A gentle giant who enjoys long naps and snack time.",
    goal: 1200,
    amount_raised: 0,
    image: "https://res.cloudinary.com/dqt5mriuz/image/upload/v1775552702/Rocky_y0klro.jpg",
    is_open: true,
    date_created: "2026-04-07T14:22:23Z",
    owner: 1,
    pledges: [],
  },
  {
    id: 5,
    title: "Flo",
    breed: "Spaniel",
    age: "Puppy",
    description: "Flo has the biggest ears and the biggest heart you've ever seen.",
    goal: 800,
    amount_raised: 0,
    image: "https://res.cloudinary.com/dqt5mriuz/image/upload/v1775552651/Flo_tongue_gueoli.jpg",
    is_open: true,
    date_created: "2026-04-07T14:22:23Z",
    owner: 1,
    pledges: [],
  },
  {
    id: 6,
    title: "Timmy",
    breed: "Terrier",
    age: "Young",
    description: "Timmy is small but mighty and ready for a home.",
    goal: 1000,
    amount_raised: 0,
    image: "https://res.cloudinary.com/dqt5mriuz/image/upload/v1775552714/Timmy_mqqt3r.jpg",
    is_open: true,
    date_created: "2026-04-07T14:22:23Z",
    owner: 1,
    pledges: [],
  },
  {
    id: 7,
    title: "Mignon",
    breed: "Mixed",
    age: "Adult",
    description: "Mignon is sweet, calm, and perfect for a relaxed home.",
    goal: 1000,
    amount_raised: 0,
    image: "https://res.cloudinary.com/dqt5mriuz/image/upload/v1775553401/MIgnon_roo563.jpg",
    is_open: true,
    date_created: "2026-04-07T14:22:23Z",
    owner: 1,
    pledges: [],
  }
];

export const oneFundraiser = allFundraisers;
